package ui.login_register;

import auto.AutoGenerateData;
import controller.login_register.LoginRegisterController;
import model.conceptual.user.Director;
import model.conceptual.user.User;
import model.shared.Constant;
import ui.DirectorUI;
import ui.Utils;
import ui.main_user.MainUserUI;

import java.util.Arrays;

public class LoginUI implements Runnable {

    private User director;

    public User getDirector() {
        return director;
    }

    public void setDirector(User director) {
        this.director = director;
    }

    @Override
    public void run() {

        LoginRegisterController ctrl = new LoginRegisterController();

        String option = null;
        String[] arrOption = {"Repeat", "Back"};
        do {
            System.out.println("LOGIN:");

            String email = Utils.readLineFromConsole("Email:");

            String password = Utils.readLineFromConsole("Password:");

            director = ctrl.doLogin(email, password);

            if (director != null) {
                System.out.println("Login Complete");
                if (director.equals(AutoGenerateData.getMainUser())) {
                    MainUserUI mainUserUI = new MainUserUI();
                    mainUserUI.run();
                } else {
                    DirectorUI directorUI = new DirectorUI(director);
                    directorUI.run();
                }
            } else {
                System.out.println("Invalid Login");
            }

            option = (String) Utils.showAndSelectOne(Arrays.asList(arrOption), "Choose an Option:");

            if (option.equals(arrOption[1])) {
                MainMenuUI menuUI = new MainMenuUI();
                menuUI.run();
            }
        } while (option.equals(arrOption[0]));
    }
}
