package ui.start;

import auto.AutoGenerateData;
import ui.login_register.MainMenuUI;

public class StartUI {

    public static void main(String[] args) {

        AutoGenerateData.autoGenerateData();

        MainMenuUI menuUI = new MainMenuUI();
        menuUI.run();
    }

}
