package auto;

import model.conceptual.club.Club;
import model.conceptual.contract.Contract;
import model.conceptual.user.Director;
import model.conceptual.user.Player;
import model.conceptual.user.User;
import model.enumerate.Country;
import model.enumerate.Foot;
import model.enumerate.Position;
import model.enumerate.Sex;
import model.shared.Company;
import model.shared.Constant;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public abstract class AutoGenerateData {

    public static User mainUser;

    public static User getMainUser() {
        return mainUser;
    }

    public static void setMainUser(User mainUser) {
        AutoGenerateData.mainUser = mainUser;
    }

    public static void autoGenerateData() {

        Company company = new Company(Constant.COMPANY_DESIGNATION);

        List<Club> clubList = new ArrayList<>();
        clubList.add(new Club("Sporting", Country.PORTUGAL));
        clubList.add(new Club("Real Madrid", Country.SPAIN));
        clubList.add(new Club("Fiorentina", Country.ITALY));
        clubList.add(new Club("Palmeiras", Country.BRAZIL));
        for (Club club : clubList) {
            Company.getClubStore().getClubList().add(club);
        }

        mainUser = new Director("Main Director", new Date(2002, 01, 15), Sex.MALE, Country.PORTUGAL, Company.getClubStore().getClubList().get(0), Constant.MAIN_EMAIL, Constant.MAIN_PASSWORD);
        Company.getUserStore().getUserList().add(mainUser);

        List<User> userList = new ArrayList<>();
        userList.add(new Player("Player-1", new Date(2000,10,10), Sex.MALE, Country.BRAZIL, Position.GK, Foot.RIGHT, Company.getClubStore().getClubList().get(0)));
        userList.add(new Player("Player-2", new Date(2000, 10, 10), Sex.FEMALE, Country.PORTUGAL, Position.CAM, Foot.RIGHT, Company.getClubStore().getClubList().get(0)));
        userList.add(new Player("Player-3", new Date(2000, 10, 10), Sex.MALE, Country.FRANCE, Position.ST, Foot.LEFT, Company.getClubStore().getClubList().get(0)));
        userList.add(new Player("Player-4", new Date(2000, 10, 10), Sex.FEMALE, Country.FRANCE, Position.RWB, Foot.LEFT, Company.getClubStore().getClubList().get(0)));

        for (User user : userList) {
            Company.getUserStore().getUserList().add(user);
        }

        List<Contract> contractList = new ArrayList<>();
        contractList.add(new Contract(Company.getUserStore().getUserList().get(0), new Date(2028, 10, 10), 500, 250, 10000000));
        contractList.add(new Contract(Company.getUserStore().getUserList().get(1), new Date(2028, 10, 10), 500, 250, 10000000));
        contractList.add(new Contract(Company.getUserStore().getUserList().get(2), new Date(2028, 10, 10), 500, 250, 10000000));
        contractList.add(new Contract(Company.getUserStore().getUserList().get(3), new Date(2028, 10, 10), 500, 250, 10000000));

        for (Contract contract : contractList) {
            Company.getContractStore().getContractList().add(contract);
        }

    }

}
