package auto;

import model.conceptual.club.Club;
import model.enumerate.Country;
import model.shared.Company;
import model.shared.Constant;

public abstract class AutoGenerateData {

    public static void autoGenerateData() {

        Company company = new Company(Constant.COMPANY_DESIGNATION);

        Club c1 = new Club("Sporting", Country.PORTUGAL);
        Club c2 = new Club("Real Madrid", Country.SPAIN);

        Company.getClubStore().getClubList().add(c1);
        Company.getClubStore().getClubList().add(c2);
    }

}
